### ISSUE TITLE
passing cropit object to onImageLoaded callback

### ISSUE THREAD

**Issue by phpMagpie** [scottcheng/cropit#100]
How do I access the relevant cropit object from callbacks such as onImageLoaded?

If I edit your plugin to pass this through to the callback function, it is then very easy to access the relevant cropit instance on my page.   

**Line 449 of cropit.js: **
```
this.options.onImageLoaded(this);
```

**My init code: **
```
onImageLoaded: function(cropitObject) {
    console.log(cropitObject.imageSrc) {
}
```

Is there a better way to do this?

**Comment by scottcheng** [comment]
Under the hood you can get the object by calling `$editor.data('cropit')`. However this should be advised against, since reading/setting properties directly on the cropit object can be unreliable and the behavior may be subject to change. You should be able to get everything through APIs, e.g. `$editor.cropit('imageSrc')`.
