### ISSUE TITLE
Best documentation ever

### ISSUE THREAD

**Issue by Unholny** [scottcheng/cropit#263]
Documentation is very good.

**Comment by Zetaphor** [comment]
I thought it went without saying, but Github uses the word "Issues" to mean a way to identify and recommend improvements to a particular part of a repo.

This issue is basically useless unless you get a lot more specific. Saying "Documentation is very bad" does not give any insight as to what problems you have and how could they could ever possibly be addressed.

What is wrong with the documentation? Is it incorrect? Is it outdated? Is it poorly written? Does it need more examples? If you want work done, you must first give something to work with.
